version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      ENV: development
      FILL: true
      MIGRATIONS: file://migration
      DSN: postgresql://Nurkhan05@localhost:5432/jana?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: jana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nurkhan05
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: