version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 8080
      ENV: development
      FILL: false
      MIGRATIONS: file://migration
      DSN: postgres://postgres:Bayernmunichtm25@localhost:5432/jana?sslmode=disable
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jana
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bayernmunichtm25
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: